# Generated by Django 5.0.2 on 2024-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
